AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - Rakefile
    - Gemfile
    - '*.gemspec'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals: 
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false
